name: docker-Azure-cicd

on: [push]

jobs:
  test:
    name: arm-template
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: test-jobs
        uses: ./pstests
        with:
          directory: arm
          template: storage.json

      - name: "deploy to azure"
        uses: ./psdeploy
        with:
          directory: arm
          template: storage.json
          appID: ${{ secrets.APPID }}
          spSecret: ${{ secrets.SERVICEPRINCIPALSECRET }}
          tenantID: ${{ secrets.TENNATID }}
          subscriptionID: ${{ secrets.SUBSCRIPTIONID }}
          resourceGroup: FRPSUG-DEMO-RG