swagger: '2.0'
info:
  description: Near Earth Object Web Service 
  title: jpl-neo
  version: v1
  termsOfService: 'http://neo.jpl.nasa.gov/'
host: api.nasa.gov
produces: 
  - application/json
consumes: 
  - application/json
schemes:
  - https
basePath: /neo/rest/v1
securityDefinitions:
  api_key:
    in: query
    name: api_key
    type: apiKey
security:
  - api_key: []

paths:
  /stats:
      get:
        operationId: CurrentNeoStatistics
        description: |
          Current NeoStatistics
        responses:
          '200':
            description: Success response
            schema:
              $ref: '#/definitions/neoStats'
  /neo/browse:
      get:
        operationId: BrowseNeoObject
        parameters:
          - in: query
            name: page
            type: integer
            default: 0
          - in: query
            name: size
            type: integer
            default: 10
        description: |
          Current NeoStatistics
        responses:
          '200':
            description: Success response
            schema:
              $ref: '#/definitions/browse'

          
definitions:
  neolist:
    properties:
      links:
        type: object
      element_count:
        type: number
      near_earth_objects:
        type: object
    type: object

  orbitalClass:
    properties: 
      orbit_class_type:
        type: string
      orbit_class_description:
        type: string
      orbit_class_range:
        type: string
    type: object

  orbitaldata:
    properties:   
      orbit_id:
        type: string
      orbit_determination_date:
        format: date-time
        type: string
      first_observation_date:
        format: date
        type: string
      last_observation_date:
        format: date
        type: string
      data_arc_in_days:
        format: int64
        type: integer
      observations_used:
        format: int64
        type: integer
      orbit_uncertainty:
        type: string
      minimum_orbit_intersection:
        type: string
      jupiter_tisserand_invariant:
        type: string
      epoch_osculation: 
        type: string
      semi_major_axis:
        type: string
      inclination:
        type: string
      ascending_node_longitude:
        type: string
      orbital_period:
        type: string
      perihelion_distance:
        type: string
      perihelion_argument:
        type: string
      aphelion_distance:
        type: string
      perihelion_time:
        type: string
      mean_anomaly:
        type: string
      mean_motion:
        type: string
      equinox:
        type: string
      orbit_class:
        $ref: '#/definitions/orbitalClass'
    type: object
  
  neoStats:
    properties:
      near_earth_object_count:
        type: integer
      close_approach_count:
        type: integer
      last_updated:
        type: string
      source:
        type: string
      nasa_jpl_url:
        type: string
    type: object

  EstimatedDiameterNumericSystem:
    properties:
      estimated_diameter_max:
        type: string
      estimated_diameter_min:
        type: string
    type: object

  EstimatedDiameter:
    properties:
      feet:
        $ref: '#/definitions/EstimatedDiameterNumericSystem'
      kilometers:
        $ref: '#/definitions/EstimatedDiameterNumericSystem'
      meters:
        $ref: '#/definitions/EstimatedDiameterNumericSystem'
      miles:
        $ref: '#/definitions/EstimatedDiameterNumericSystem'
    type: object



  Neoobject:
    properties:
      links:
        type: object
      neo_reference_id:
        type: string
      name:
        type: string
      designation:
        type: string
      nasa_jpl_url:
        type: string
      absolute_magnitude_h:
        type: string  
      estimated_diameter:
        $ref: "#/definitions/EstimatedDiameter"
      is_potentially_hazardous_asteroid: 
        type: boolean
      orbital_data: 
        $ref: "#/definitions/orbitaldata"
      is_sentry_object:
        type: boolean
    type: object

  page: 
    properties:
      size:
        type: integer
      total_elements:
        type: integer
      total_pages:
        type: integer
      number:
        type: integer
    type: object

  browse:
    properties:
      links:
        type: object
      page:
        $ref: "#/definitions/page"
      near_earth_objects: 
        items:
          $ref: "#/definitions/Neoobject"
        type: array
    type: object