#cloud-config
vyos_config_commands:
  - set system host-name 'RTRSIO1'
  - set interfaces ethernet eth1 address '172.18.0.254/24'
  - set service dhcp-server shared-network-name LAN subnet 172.18.0.0/24 default-router '172.18.0.254'
  - set service dhcp-server shared-network-name LAN subnet 172.18.0.0/24 dns-server '1.1.1.1'
  - set service dhcp-server shared-network-name LAN subnet 172.18.0.0/24 domain-name 'SIO.lab'
  - set service dhcp-server shared-network-name LAN subnet 172.18.0.0/24 range 0 start '172.18.0.1'
  - set service dhcp-server shared-network-name LAN subnet 172.18.0.0/24 range 0 stop '172.18.0.252'
  - set nat source rule 100 outbound-interface 'eth0'
  - set nat source rule 100 source address '172.18.0.0/24'
  - set nat source rule 100 translation address 'masquerade'